import { Header } from "@/components/Header";
import { SiteFooter } from "@/components/SiteFooter";

export default function Disclaimer() {
  return (
    <div className="min-h-screen flex flex-col">
      <Header audience="learn" />

      <main className="flex-1 py-12">
        <div className="container px-4 max-w-3xl mx-auto prose prose-sm dark:prose-invert">
          <h1>Disclaimer</h1>

          <h2>General Information Only</h2>
          <p>
            The material presented on the Little Minds website is provided for general
            informational and educational purposes only. It is not an attempt to practice medicine,
            psychology, or any other form of professional healthcare, and does not constitute
            medical advice, diagnosis, or treatment. All use of this website and its content is at
            your own risk.
          </p>

          <h2>Not a Substitute for Professional Help</h2>
          <p>
            The information on this website should not replace consultation with a qualified
            healthcare provider, therapist, counselor, or other mental health professional. Always
            seek the advice of a qualified professional with any questions you may have regarding a
            medical or mental health condition. Never disregard professional advice or delay in
            seeking it because of something you have read on this website.
          </p>

          <h2>No Doctor/Patient or Therapist/Client Relationship</h2>
          <p>
            Use of this website does not create a doctor/patient, therapist/client, or any other
            professional relationship between you and Little Minds or its creator. The content is
            not intended to establish such a relationship and should not be relied upon as a
            substitute for professional consultation.
          </p>

          <h2>Emergency Situations</h2>
          <p>
            If you believe you or someone else is experiencing a medical or mental health emergency,
            please call your local emergency services immediately. Do not rely on this website for
            emergency assistance.
          </p>

          <h2>AI Chat Assistant ("Little Minds Helper")</h2>
          <p>
            Little Minds Helper is an automated tool designed to provide general information and
            support navigation of this website. It is not a therapist, counselor, or crisis
            intervention service. It cannot diagnose conditions, prescribe treatments, or provide
            professional mental health care. A notice is displayed before your first message
            reminding you that the assistant is an AI, not a real person or doctor. Responses
            generated by Little Minds Helper may contain errors. Always verify important information
            with a trusted adult or qualified professional. Conversations are not stored, are not
            monitored in real time, and are not reviewed by a human.
          </p>
          <p>
            The chat applies automated safety filters that block harmful, sexual, violent, or
            otherwise inappropriate content; remove personal information (such as emails, phone
            numbers, addresses, or school names) from messages before they reach the AI; and
            automatically attach crisis hotline information when language suggesting self-harm or
            suicide is detected. These filters are safety guardrails. They are <strong>not</strong>{" "}
            a substitute for emergency services or professional mental health care. If you or someone
            you know is in crisis, contact your local emergency services or a crisis hotline
            immediately. The crisis-language safety response is a best-effort feature and is not
            guaranteed to detect every situation.
          </p>

          <h2>Content Aimed at Children</h2>
          <p>
            Some sections of this website are designed for children and young people. While we strive
            to provide age-appropriate, helpful information, parents and guardians should supervise
            their children's use of this website and any actions taken based on its content.
          </p>
          <p>
            Children (and all users) should be reminded never to type passwords, financial details,
            home addresses, phone numbers, school names, or other sensitive personal information into
            any input field on this website — including the AI chat, the private journal, the contact
            form, or the donation inquiry form. Little Minds will never ask for this information.
          </p>
          <p>
            This website does not automatically collect personal information from any visitor of any
            age. The only personal information we receive is what users voluntarily choose to submit
            through our contact or donation inquiry forms. To comply with the Children's Online
            Privacy Protection Act (COPPA), which protects children under the age of 13, the contact
            form requires users to confirm they are 13 or older before submitting. The donation
            inquiry form requires users to be 18 or older.
          </p>

          <h2>Third Party Links and Resources</h2>
          <p>
            This website may contain links to external websites and resources. Little Minds does not
            control, endorse, or guarantee the accuracy of content on third party websites. You
            access external links at your own risk, and Little Minds is not responsible for any
            content, services, or outcomes from third party websites. You should review their own
            terms and privacy policies.
          </p>

          <h2>Crisis Helplines and Local Resources</h2>
          <p>
            The "Help Now" drawer and the Parent "Find Support" page list emergency numbers,
            crisis helplines, and other local resources for selected countries. The specific
            resources available vary by country and may include mental health support lines, child
            and family services, or directories that help you search for a therapist — Little Minds
            does not provide therapy itself and cannot guarantee that any listed service will be
            available, free, or suitable for your situation. Not every country is currently
            listed, and details such as phone numbers and operating hours can change without notice.
            Always verify information directly with the service provider, and in an emergency call
            your local emergency number.
          </p>

          <h2>Data Retention</h2>
          <p>
            Because Little Minds stores all information (such as journals, progress, favorites, and
            preferences) locally on your device using your browser's storage, we cannot recover or
            back up your data. If you clear your browser data, use a different browser, or lose your
            device, your saved information will be permanently deleted. Little Minds is not
            responsible for any data loss.
          </p>

          <h2>No Guarantees</h2>
          <p>
            While we make every effort to ensure the information on this website is accurate and up
            to date, Little Minds makes no representations or warranties of any kind, express or
            implied, about the completeness, accuracy, reliability, or suitability of the
            information, activities, or tools provided. Any reliance you place on such information
            is strictly at your own risk.
          </p>

          <h2>Limitation of Liability</h2>
          <p>
            Little Minds, its creator, contributors, and affiliates shall not be liable for any
            loss, injury, claim, liability, or damage of any kind resulting from your use of this
            website or any information provided on it, including but not limited to any direct,
            indirect, incidental, consequential, or punitive damages.
          </p>

          <h2>Nature of This Project</h2>
          <p>
            Little Minds is a free personal project created to help children, parents, and
            individuals learn about mental health and wellbeing. No profit is made from this
            website. It is not a registered charity or formal organisation and operates as a
            personal educational project.
          </p>

          <p className="text-xs text-muted-foreground mt-8">
            Last updated: April 2026
          </p>
        </div>
      </main>

      <SiteFooter />
    </div>
  );
}
