import { Header } from "@/components/Header";
import { SiteFooter } from "@/components/SiteFooter";

export default function Disclaimer() {
  return (
    <div className="min-h-screen flex flex-col">
      <Header audience="learn" />

      <main className="flex-1 py-12">
        <div className="container px-4 max-w-3xl mx-auto prose prose-sm dark:prose-invert">
          <h1>Disclaimer</h1>

          <h2>General Information Only</h2>
          <p>
            The material presented on the Little Minds website is provided for general
            informational and educational purposes only. It is not an attempt to practice medicine,
            psychology, or any other form of professional healthcare, and does not constitute
            medical advice, diagnosis, or treatment.
          </p>

          <h2>Not a Substitute for Professional Help</h2>
          <p>
            The information on this website should not replace consultation with a qualified
            healthcare provider, therapist, counselor, or other mental health professional. Always
            seek the advice of a qualified professional with any questions you may have regarding a
            medical or mental health condition. Never disregard professional advice or delay in
            seeking it because of something you have read on this website.
          </p>

          <h2>No Doctor/Patient or Therapist/Client Relationship</h2>
          <p>
            Use of this website does not create a doctor/patient, therapist/client, or any other
            professional relationship between you and Little Minds or its creator. The content is
            not intended to establish such a relationship and should not be relied upon as a
            substitute for professional consultation.
          </p>

          <h2>Emergency Situations</h2>
          <p>
            If you believe you or someone else is experiencing a medical or mental health emergency,
            please call your local emergency services immediately. Do not rely on this website for
            emergency assistance.
          </p>

          <h2>AI Chat Assistant ("Little Minds Helper")</h2>
          <p>
            Little Minds Helper is an automated tool designed to provide general information and
            support navigation of this website. It is not a therapist, counselor, or crisis
            intervention service. It cannot diagnose conditions, prescribe treatments, or provide
            professional mental health care. Responses generated by Little Minds Helper may contain
            errors. Always verify important information with a trusted adult or qualified
            professional.
          </p>

          <h2>Content Aimed at Children</h2>
          <p>
            Some sections of this website are designed for children and young people. While we strive
            to provide age-appropriate, helpful information, parents and guardians should supervise
            their children's use of this website and any actions taken based on its content. This
            website does not collect personal information from children.
          </p>

          <h2>Third Party Links and Resources</h2>
          <p>
            This website may contain links to external websites and resources. Little Minds does not
            control, endorse, or guarantee the accuracy of content on third party websites. You
            access external links at your own risk and should review their own terms and privacy
            policies.
          </p>

          <h2>Data Retention</h2>
          <p>
            Because Little Minds stores all information (such as journals, progress, favorites, and
            preferences) locally on your device using your browser's storage, we cannot recover or
            back up your data. If you clear your browser data, use a different browser, or lose your
            device, your saved information will be permanently deleted. Little Minds is not
            responsible for any data loss.
          </p>

          <h2>No Guarantees</h2>
          <p>
            While we make every effort to ensure the information on this website is accurate and up
            to date, Little Minds makes no representations or warranties of any kind, express or
            implied, about the completeness, accuracy, reliability, or suitability of the
            information, activities, or tools provided. Any reliance you place on such information
            is strictly at your own risk.
          </p>

          <h2>Limitation of Liability</h2>
          <p>
            Little Minds, its creator, contributors, and affiliates shall not be liable for any
            loss, injury, claim, liability, or damage of any kind resulting from your use of this
            website or any information provided herein, including but not limited to any direct,
            indirect, incidental, consequential, or punitive damages.
          </p>

          <h2>Non Profit Nature</h2>
          <p>
            Little Minds is a non profit project created to help children, parents, and individuals
            learn about mental health and wellbeing. It is not a healthcare organization or
            registered charity.
          </p>

          <p className="text-xs text-muted-foreground mt-8">
            Last updated: March 2026
          </p>
        </div>
      </main>

      <SiteFooter />
    </div>
  );
}
