import { Header } from "@/components/Header";
import { SiteFooter } from "@/components/SiteFooter";

export default function Terms() {
  return (
    <div className="min-h-screen flex flex-col">
      <Header audience="learn" />

      <main className="flex-1 py-12">
        <div className="container px-4 max-w-3xl mx-auto prose prose-sm dark:prose-invert">
          <h1>Terms of Use</h1>

          <p>
            By accessing and using the Little Minds website, you accept and agree to be bound by
            these Terms of Use. If you do not agree, please do not use this website.
          </p>
          <p>
            If you are under the age of 18, you must review these Terms with a parent or guardian.
            By using this website, you represent that your parent or guardian has reviewed and agreed
            to these Terms on your behalf.
          </p>

          <h2>Use of This Website</h2>
          <p>
            This website is intended to provide general mental health information and educational
            resources. You may use the content for personal, non-commercial purposes only. You agree
            not to misuse the website or its content in any way that could damage, disable, or
            impair its functionality.
          </p>

          <h2>Accuracy of Information</h2>
          <p>
            While we strive to keep the information on this website accurate and current, we do not
            warrant that the content is complete, reliable, or error-free. The information is
            provided "as is" without any representations or warranties.
          </p>

          <h2>User Conduct</h2>
          <p>You agree not to:</p>
          <ul>
            <li>Use this website for any unlawful or harmful purpose</li>
            <li>Attempt to gain unauthorized access to any part of the website</li>
            <li>Reproduce, distribute, or modify the website content without permission</li>
            <li>Use automated tools to scrape or extract content from this website</li>
            <li>Submit false, misleading, or harmful information through any forms on this site</li>
            <li>Enter passwords, financial information, government identifiers, or other sensitive credentials into any input field on this website (including the AI chat, journal, contact form, or donation form). Little Minds will never ask for this information.</li>
          </ul>

          <h2>AI Chat Assistant</h2>
          <p>
            The Little Minds Helper chat feature is provided for informational purposes only. By
            using the chat, you acknowledge that:
          </p>
          <ul>
            <li>Responses are generated by automated technology and may contain errors</li>
            <li>The chat is not a substitute for professional mental health support</li>
            <li>The chat does not provide therapy, counseling, or crisis intervention</li>
            <li>You should not share sensitive personal information through the chat, including passwords, financial details, or other private credentials</li>
            <li>Chat conversations are not stored or monitored in real time</li>
          </ul>
          <p>
            To keep the chat safe and age-appropriate, automated safety filters are applied to your
            messages before they reach the AI. These include filters for profanity, sexual content,
            graphic violence, drugs, weapons, attempts to override the assistant's safety rules, and
            personal information (such as emails, phone numbers, addresses, or school names, which
            are removed automatically). When the chat detects language suggesting self-harm or
            suicidal thoughts, it automatically displays crisis hotline information at the top of the
            response. By using the chat, you agree not to attempt to bypass, manipulate, or exploit
            these safety filters.
          </p>
          <p>
            Responses generated by the AI are for your personal use only. You may not use
            AI-generated responses for commercial purposes or represent them as professional advice.
          </p>

          <h2>Intellectual Property</h2>
          <p>
            All content on this website, including text, graphics, logos, and design, is the
            property of Little Minds unless otherwise stated. You may not reproduce or distribute
            this content without written permission, except for personal, non-commercial use.
          </p>

          <h2>External Links</h2>
          <p>
            This website may contain links to third party websites. These links are provided for
            your convenience only. Little Minds has no control over the content of external sites
            and is not responsible for their content or practices.
          </p>

          <h2>Privacy</h2>
          <p>
            Little Minds respects your privacy. This website does not automatically collect personal
            information from any visitor of any age. The only personal information we receive is
            what you voluntarily choose to submit through our contact form or donation inquiry form.
            Some features (such as activity progress and favorites) use your browser's local storage
            and are not transmitted to any server.
          </p>
          <p>
            To comply with the Children's Online Privacy Protection Act (COPPA), which protects
            children under the age of 13, our contact form requires users to confirm they are 13 or
            older before submitting. The donation inquiry form requires users to be 18 or older.
            These age requirements ensure that we do not knowingly collect personal information from
            children under 13.
          </p>

          <h2>Data and Storage</h2>
          <p>
            Because your journals, progress, and favorites are stored only on your local device,
            Little Minds cannot recover, move, or back up this data. You are solely responsible for
            maintaining your device and browser settings. We are not responsible for any loss of data
            caused by clearing your browser cache, device damage, or any other reason.
          </p>

          <h2>Donations</h2>
          <p>
            Little Minds provides a donation inquiry form that allows you to express interest in
            supporting this project. You must be 18 years of age or older to submit a donation
            inquiry. No financial transactions take place on this website. If you submit a donation
            inquiry, we will contact you by email to discuss next steps. Little Minds is a free
            personal project — not a registered charity or government entity — and donations are
            not tax deductible.
          </p>

          <h2>Limitation of Liability</h2>
          <p>
            To the fullest extent permitted by law, Little Minds and its creator shall not be held
            liable for any damages arising from your use of this website, including but not limited
            to direct, indirect, incidental, consequential, or punitive damages.
          </p>

          <h2>Image Credits</h2>
          <p>
            The hero photograph displayed on the Little Minds homepage — showing two children
            sitting in a meadow reading a book together — is a stock photograph licensed via{" "}
            <a href="https://www.pexels.com" target="_blank" rel="noopener noreferrer" className="text-primary underline underline-offset-2 hover:opacity-80">Pexels</a>{" "}
            under the free Pexels License, which permits commercial and non-commercial use without
            attribution. The children pictured are not affiliated with Little Minds and do not
            personally endorse this website or its content.
          </p>

          <h2>Changes to These Terms</h2>
          <p>
            We reserve the right to update these Terms of Use at any time. Continued use of the
            website after changes constitutes your acceptance of the updated terms.
          </p>

          <h2>Contact</h2>
          <p>
            If you have questions about these Terms of Use, please reach out through our{" "}
            <a href="/contact">contact page</a>.
          </p>

          <p className="text-xs text-muted-foreground mt-8">
            Last updated: April 2026
          </p>
        </div>
      </main>

      <SiteFooter />
    </div>
  );
}
